language: r
sudo: required

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_binary_packages:
  - moments
  - testthat
  - knitr
  - plyr
  - roxygen2
  
r_packages:
  - mvbutils
  - parallel
  
r_github_packages:
  - pnnl/Smisc

branches:
  only:
    - master

notifications:
  email:
    recipients:
    - lucas.tate@pnnl.gov
    - landon.sego@pnnl.gov
    on_success: change
    on_failure: change
